apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
    namespace: amos # Namespaced to amos
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
